[package]
name = "ink-dap-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ink-dap-server"
path = "src/main.rs"

[dependencies]
dap = "0.4.1-alpha1"
serde_json = "1.0.145"

anyhow = "1"
polkavm = "0.30"
